### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by guilhem** [ccin2p3/go-freeipa#2]
Hi,
I'm the author of https://github.com/guilhem/freeipa-issuer, and I'm using a lot `go-freeipa`.
As @tehwalris as put his work in archive, do you want to put your repository as principal work?

**Comment by riton** [comment]
Hi @guilhem . Short answer: **yes**.

I plan to make a proper release of this _fork_ and IN2P3-CC will maintain it. We're extensively using RedHat IDM here and we'll try to support the best we can the development of this library.

**Comment by guilhem** [comment]
> Hi @guilhem . Short answer: **yes**.

:tada: 

> I plan to make a proper release of this _fork_ and IN2P3-CC will maintain it. We're extensively using RedHat IDM here and we'll try to support the best we can the development of this library.

Don't hesitate if you need some help (no Paris/Lyon fight here :wink:)
Just having all your patches in a release would be wonderful.

**Comment by riton** [comment]
`v1.1.0` was just released.

The package name was changed from `github.com/tehwalris/go-freeipa` to `github.com/ccin2p3/go-freeipa` in the process.

Feel free to submit patches or issues if you need a functionality that is missing.

**Comment by guilhem** [comment]
Thx @riton 
Just for the beauty of the repo, can you "unfork" this repository?
It will be more accessible through search, etc.

**Comment by tehwalris** [comment]
I'd be happy to link this fork in the description of my archived repo to make it easier for people to find.

**Comment by riton** [comment]
> Thx @riton Just for the beauty of the repo, can you "unfork" this repository? It will be more accessible through search, etc.

While I understand the motivation, we'd prefer to keep this link and origin visible.

@tehwalris I've just seen the direct link in your archived repo `README.md`. Thanks :pray:
