### ISSUE TITLE
Cannot install the library

### ISSUE THREAD

**Issue by PrMinisterGR** [ccin2p3/go-freeipa#6]
command error: err: exit status 1: stderr: go: finding module for package github.com/ccin2p3/go-freeipa
go: finding module for package github.com/ccin2p3/go-freeipa
module github.com/ccin2p3/go-freeipa@latest found (v1.1.0), but does not contain package github.com/ccin2p3/go-freeipa

**Comment by riton** [comment]
Hi @PrMinisterGR 

You're not giving any context or any information I can use to help you.

I'm still gonna give it a try:

Here's a `main.go` file:
```
package main

import (
        "github.com/ccin2p3/go-freeipa/freeipa"
)

func main() {
        var _ freeipa.Client
}
```

Here's my  `go.mod` file:

```
module whatever

go 1.19      
                                                     
require github.com/ccin2p3/go-freeipa v1.1.0
                                                     
require (
        github.com/hashicorp/go-uuid v1.0.2 // indirect
        github.com/jcmturner/aescts/v2 v2.0.0 // indirect
        github.com/jcmturner/dnsutils/v2 v2.0.0 // indirect
        github.com/jcmturner/gofork v1.0.0 // indirect
        github.com/jcmturner/goidentity/v6 v6.0.1 // indirect
        github.com/jcmturner/gokrb5/v8 v8.4.2 // indirect
        github.com/jcmturner/rpc/v2 v2.0.3 // indirect
        github.com/pkg/errors v0.9.1 // indirect
        golang.org/x/crypto v0.0.0-20201112155050-0c6587e931a9 // indirect
        golang.org/x/net v0.0.0-20200114155413-6afb5195e5aa // indirect
)
```

and here's the output of my `go mod tidy` command:

```
❯ go mod tidy                                                                                             
go: finding module for package github.com/ccin2p3/go-freeipa/freeipa                                                                                                                                                 
go: found github.com/ccin2p3/go-freeipa/freeipa in github.com/ccin2p3/go-freeipa v1.1.0                                                                                                                              
go: downloading golang.org/x/crypto v0.0.0-20201112155050-0c6587e931a9                                                                                                                                               
go: downloading github.com/davecgh/go-spew v1.1.0  
```

It does **not** complain on my workstation.

I'm gonna wait for more context on your error to continue investigations.

**Comment by PrMinisterGR** [comment]
Hi, I was swapping from the old tehwalris version, and I was getting this error constantly when trying to pull this one with go get. I updated VSCode and I just cleaned the go cache and it seems to be working for now.

Thank you for the quick response.

**Comment by PrMinisterGR** [comment]
Apologies to open this again, I am not sure if it's an issue with the module, or a general Go issue when I try to replace the old library with this fork in some of my projects.
This is how my import looks:
```
package uiterminal

import (
	"errors"
	"log"

	mmidam "git.cps.metro-markets.org/it-tools/mmidam"
	survey "github.com/AlecAivazis/survey/v2"
	freeipa "github.com/ccin2p3/go-freeipa"
	"github.com/gookit/color"
	"github.com/kr/pretty"
)

```

And this is the upper part of my go.mod file

```
module git.cps.metro-markets.org/it-tools/ui-terminal

go 1.18
require github.com/ccin2p3/go-freeipa v1.1.1

```

Unfortunately when I have the file I need to work with open, I get this:
<img width="382" alt="image" src="https://user-images.githubusercontent.com/12447314/194538488-f621b03d-a913-4b50-abd1-b9268b35ee1d.png">


And when I try to install it I get this:

<img width="382" alt="image" src="https://user-images.githubusercontent.com/12447314/194538592-4534644c-2400-4e0e-a6bf-8ba6f189e0c7.png">



This is the trace:

```
[Error - 1:01:08 PM] Request workspace/executeCommand failed.
  Message: err: exit status 1: stderr: go: finding module for package github.com/ccin2p3/go-freeipa
go: finding module for package github.com/ccin2p3/go-freeipa
module github.com/ccin2p3/go-freeipa@latest found (v1.1.1), but does not contain package github.com/ccin2p3/go-freeipa

  Code: 0 
[Error - 1:01:08 PM] 2022/10/07 13:01:08 command error: err: exit status 1: stderr: go: finding module for package github.com/ccin2p3/go-freeipa
go: finding module for package github.com/ccin2p3/go-freeipa
module github.com/ccin2p3/go-freeipa@latest found (v1.1.1), but does not contain package github.com/ccin2p3/go-freeipa
```

Any idea or assistance would be really appreciated. Thank you!

**Comment by riton** [comment]
Hi,

You should change your import from `github.com/ccin2p3/go-freeipa` to `github.com/ccin2p3/go-freeipa/freeipa`

See https://github.com/ccin2p3/go-freeipa/blob/develop/examples/list_hosts/main.go#L10 for a complete example.

**Comment by PrMinisterGR** [comment]
This did it, thank you again!
